"""Pydantic models for Coda API."""

# Import common types and utilities
from .common import (
    AccessType,
    # Error models
    ApiError,
    BadRequestError,
    CodaDetail,
    DocReference,
    # Response models
    DocumentMutateResponse,
    FolderReference,
    ForbiddenError,
    FormulaDetail,
    GoneError,
    Icon,
    Image,
    # Enums
    Method,
    NotFoundError,
    # Reference models
    PageReference,
    # Pagination
    PaginationMetadata,
    PersonValue,
    SortBy,
    SortDirection,
    TableType,
    TooManyRequestsError,
    UnauthorizedError,
    UnprocessableEntityError,
    User,
    ValidationError,
    ValueFormat,
    WorkspaceReference,
)

# Import doc-related models
from .docs import (
    Doc,
    DocCategory,
    DocCategoryList,
    DocCreate,
    DocDelete,
    DocList,
    DocPublish,
    DocPublished,
    DocPublishMode,
    DocSize,
    DocumentCreationResult,
    DocUpdate,
    DocUpdateResult,
    PublishResult,
    UnpublishResult,
)

# Import page export models
from .exports import (
    BeginPageContentExportRequest,
    BeginPageContentExportResponse,
    PageContentExportStatusResponse,
)

# Import formula models
from .formulas import (
    Formula,
    FormulaList,
    FormulaReference,
)

# Import page-related models
from .pages import (
    CanvasPageContent,
    DeletePageContentRequest,
    DeletePageContentResult,
    EmbedPageContent,
    Page,
    PageContent,
    PageContentElement,
    PageContentElementList,
    PageContentUpdate,
    PageCreate,
    PageCreateResult,
    PageDeleteResult,
    PageList,
    PageUpdate,
    PageUpdateResult,
)

# Import row-related models
from .rows import (
    CellEdit,
    CellValue,
    CurrencyValue,
    ImageUrlValue,
    LinkedDataObject,
    PushButtonResult,
    RichSingleValue,
    RichValue,
    Row,
    RowCreate,
    RowDeleteResult,
    RowDetail,
    RowEdit,
    RowList,
    RowsDelete,
    RowsDeleteResult,
    RowsSortBy,
    RowsUpsert,
    RowsUpsertResult,
    RowUpdate,
    RowUpdateResult,
    RowValue,
    ScalarValue,
    UrlValue,
    Value,
)

# Import table-related models
from .tables import (
    ButtonColumnFormat,
    CheckboxColumnFormat,
    Column,
    ColumnDetail,
    ColumnFormat,
    ColumnFormatType,
    ColumnList,
    ColumnReference,
    CurrencyColumnFormat,
    DateColumnFormat,
    DateTimeColumnFormat,
    DurationColumnFormat,
    EmailColumnFormat,
    ImageReferenceColumnFormat,
    Layout,
    LinkColumnFormat,
    NumericColumnFormat,
    ReferenceColumnFormat,
    ScaleColumnFormat,
    SelectColumnFormat,
    SelectOption,
    SimpleColumnFormat,
    SliderColumnFormat,
    Sort,
    Table,
    TableList,
    TableReference,
    TimeColumnFormat,
)

__all__ = [
    # Common - Enums
    "Method",
    "AccessType",
    "SortDirection",
    "SortBy",
    "ValueFormat",
    "TableType",
    # Common - Error models
    "ApiError",
    "ValidationError",
    "CodaDetail",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "GoneError",
    "UnprocessableEntityError",
    "TooManyRequestsError",
    # Common - Pagination
    "PaginationMetadata",
    # Common - Reference models
    "PageReference",
    "Icon",
    "Image",
    "FormulaDetail",
    "PersonValue",
    "DocReference",
    "FolderReference",
    "WorkspaceReference",
    "User",
    # Common - Response models
    "DocumentMutateResponse",
    # Docs
    "Doc",
    "DocList",
    "DocCreate",
    "DocUpdate",
    "DocUpdateResult",
    "DocumentCreationResult",
    "DocDelete",
    "DocPublish",
    "DocPublished",
    "DocSize",
    "DocCategory",
    "DocCategoryList",
    "PublishResult",
    "UnpublishResult",
    "DocPublishMode",
    # Tables
    "Layout",
    "ColumnFormatType",
    "TableReference",
    "ColumnReference",
    "Column",
    "ColumnDetail",
    "ColumnList",
    "Table",
    "TableList",
    "Sort",
    "SimpleColumnFormat",
    "ReferenceColumnFormat",
    "NumericColumnFormat",
    "CurrencyColumnFormat",
    "DateColumnFormat",
    "TimeColumnFormat",
    "DateTimeColumnFormat",
    "DurationColumnFormat",
    "EmailColumnFormat",
    "LinkColumnFormat",
    "ImageReferenceColumnFormat",
    "SliderColumnFormat",
    "ScaleColumnFormat",
    "ButtonColumnFormat",
    "CheckboxColumnFormat",
    "SelectColumnFormat",
    "SelectOption",
    "ColumnFormat",
    # Rows
    "RowsSortBy",
    "ScalarValue",
    "Value",
    "CellValue",
    "CellEdit",
    "RowEdit",
    "Row",
    "RowDetail",
    "RowList",
    "RowUpdate",
    "RowUpdateResult",
    "RowCreate",
    "RowsUpsert",
    "RowsUpsertResult",
    "RowsDelete",
    "RowsDeleteResult",
    "RowDeleteResult",
    "PushButtonResult",
    "LinkedDataObject",
    "UrlValue",
    "ImageUrlValue",
    "CurrencyValue",
    "RowValue",
    "RichSingleValue",
    "RichValue",
    # Pages
    "Page",
    "PageList",
    "PageContent",
    "CanvasPageContent",
    "EmbedPageContent",
    "PageCreate",
    "PageContentUpdate",
    "PageUpdate",
    "PageCreateResult",
    "PageUpdateResult",
    "PageDeleteResult",
    # Page Content Elements (for surgical updates)
    "PageContentElement",
    "PageContentElementList",
    "DeletePageContentRequest",
    "DeletePageContentResult",
    # Exports
    "BeginPageContentExportRequest",
    "BeginPageContentExportResponse",
    "PageContentExportStatusResponse",
    # Formulas
    "Formula",
    "FormulaList",
    "FormulaReference",
]
